<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.3.4';
$moduleRevision = 'be006143601e41ba453f4f8211042c4c0ff2001f';
$moduleWikiUrl = 'https://www.docs.modulesgarden.com/Amazon_EC2_For_WHMCS';
