version: '3.3.0'
systemName: 'directadminExtended'
name: 'DirectAdmin Extended'
description: 'Modules Garden Module Framework.<br>For more info visit our <a href="http://www.docs.modulesgarden.com/CHANGE_ME" style="color: #4169E1;" target="_blank">Wiki</a>.'
clientareaName: 'DirectAdminExtended'
author: '<a href="http://www.modulesgarden.com" targer="_blank">ModulesGarden</a>'
moduleIcon: 'directadmin_extended'
debug: 1
