<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.7.1';
$moduleRevision = '8b5881c65bad18cf78da2a701b275388a170208d';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/WordPress_Manager_For_WHMCS';
