<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.5.1';
$moduleRevision = '4495243abc42e96f5afe80daeb671e1d7d0dfa6e';
$moduleWikiUrl = 'https://www.docs.modulesgarden.com/Hetzner_VPS_For_WHMCS';