<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '3.7.0';
$moduleRevision = 'b9a8cd1dcaad832dd6c01bc0cb87bd2d1b1812ab';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/DirectAdmin_Extended_For_WHMCS';