<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.0.1';
$moduleRevision = 'c640c137e09bea4f8c1d05ea8208728f925077ea';
$moduleWikiUrl = 'https://www.docs.modulesgarden.com/Vultr_VPS_For_WHMCS';