<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.2.1';
$moduleRevision = 'a4588f442816e6f4c34e7f4edd4d04c5a22e3aba';
$moduleWikiUrl = 'https://www.docs.modulesgarden.com/Google_Cloud_Virtual_Machines_For_WHMCS';