home: 
    icon: 'lu-nav__link-icon lu-zmdi lu-zmdi-home'
LoggerManager:
    icon: 'lu-nav__link-icon lu-zmdi lu-zmdi-assignment'
documentation:
    icon: 'lu-nav__link-icon lu-zmdi lu-zmdi-file-text'
    externalUrl: "https://www.docs.modulesgarden.com/OVH_VPS_And_Dedicated_Servers_For_WHMCS"
