<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.3.0';
$moduleRevision = '8cab4d50354a97ceb352e2fcb4c245f89174492c';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/Cloud_Billing_For_WHMCS';