<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.7.0-i236';
$moduleRevision = '16937e119d7f95cebaf94d6c6b33459700cf70c3';
$moduleWikiUrl = 'https://www.docs.modulesgarden.com/DigitalOcean_Droplets_For_WHMCS';