<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.2.1';
$moduleRevision = 'a1a7c54e9fa0dd7c1fc7f4efa41d1785f039b33e';
$moduleWikiUrl = 'https://www.docs.modulesgarden.com/OVH_VPS_And_Dedicated_Servers_For_WHMCS';