<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '3.7.1';
$moduleRevision = 'e72f9e402069d6bdfdeab9dfb73474d59232d011';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/DirectAdmin_Extended_For_WHMCS';