<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.3.8';
$moduleRevision = 'ca10ba5f7a04f35e5d7eea8ab2c3ca6ec7401e4d';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/';